# 网站的基本信息
site:
  tab: FeltSquirrel727 # 浏览器标签栏上显示的文本
  title: FeltSquirrel727 # 网站的标题
  description: FeltSquirrel727 分享编程旅程、技术探索和生活趣事的地方
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://shiki.style/themes
  date_format: YYYY-MM-DD ddd # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 首页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: 博客
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 所有文章
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: 技术
          href: /blog/category/技术
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: 生活
          href: /blog/category/生活
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # 子菜单项配置
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 友链
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: 联系
      href: "mailto:tbeducn@gmail.com"
      target: _blank # 在新标签页打开
      svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: FeltSquirrel727 # 用户名
  site: "https://www.tbedu.top" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://mr.baidu.com/r/1vpwVIFGtDq?f=cp&rs=1011739487&ruk=YE2B0oUHIpmOcIx99pZIhA&u=4b5d73d51c8b223d&sid_for_share=99125_3" # 链接
        ariaLabel: Baidu # 图标的可访问性标签
        title: Baidu # 图标的悬浮标题
        svg: "ri:baidu-line"
      - href: "https://github.com/TBedu"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3461568163481938"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.youtube.com/@FeltSquirrel727"
        ariaLabel: YouTube
        title: YouTube
        svg: "ri:youtube-line"
  footer:
    social:
      - href: "https://mr.baidu.com/r/1vpwVIFGtDq?f=cp&rs=1011739487&ruk=YE2B0oUHIpmOcIx99pZIhA&u=4b5d73d51c8b223d&sid_for_share=99125_3" # 链接
        ariaLabel: Baidu # 图标的可访问性标签
        title: Baidu # 图标的悬浮标题
        svg: "ri:baidu-line"
      - href: "https://github.com/TBedu"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3461568163481938"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.youtube.com/@FeltSquirrel727"
        ariaLabel: YouTube
        title: YouTube
        svg: "ri:youtube-line"
